[app]
name = "项目的开端"
env = "dev"
debug = true
version = "v0.0.1"
listen = 8090
salt = "BWqzqzeCq8L$8obW"
host = "http://127.0.0.1:8090"
google_secret = "DXQHUUBTVBVSFEIA"

[cnf]
token_expire_hours = 24

[log]
gorm_log = true

[jwt]
secret = "U0042X2V^Lpb4OljBaHuinE$"

[aes]
key = "SFq3SIAPZY7t3mjj"
iv = "lR25Ojr5Nq9uv9Lu"

[db]
connection = "mysql"
host = "127.0.0.1"
port = "4306"
database = "beginning"
username = "root"
password = "MySQL@9527"

[cache]
drive = "redis"

[redis]
host = "127.0.0.1"
port = "7379"
auth = "Redis@9527"
database = 0

[fs]
drive = "cos"
secret_id = ""
secret_key = ""
bucket = ""
region = "ap-shanghai"

[queue]
drive = "rabbit-mq"

[rabbit-mq]
host = "127.0.0.1"
port = "6672"
user = "admin"
pass = "Rabbit@9527"
vhost = "/"

[wx-applet]
app_id = ""
app_secret = ""
