#
# WARNING you can build with register http://your-id.m.daocloud.io
#

# database mysql
beginning-mysql:
    build: ./mysql
    privileged: true
    #restart: always
    ports:
        # Allow client to access 3306
        - "4306:3306"
    volumes:
        # NOTE: your data will be stored in ./mysql
        - ./mysql/data:/var/lib/mysql
        # Configs
        - ./mysql/my.cnf:/etc/my.cnf
        # Logs
        - ./mysql/logs:/var/log/mysql
        # Date
        - /etc/localtime:/etc/localtime:ro
    environment:
        # Password for root
        - MYSQL_ROOT_PASSWORD=MySQL@9527

# database redis
beginning-redis:
    build: ./redis
    privileged: true
    #restart: always
    ports:
        - "7379:6379"
    volumes:
        - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
        - ./redis/data:/data

# mq rabbit
beginning-rabbit-mq:
    image: registry.cn-qingdao.aliyuncs.com/herui-public/rabbitmq
    environment:
        - RABBITMQ_QUEUE=default
        - RABBITMQ_HOST=rabbitmq
        - RABBITMQ_PORT=5672
        - RABBITMQ_DEFAULT_VHOST=/
        - RABBITMQ_DEFAULT_USER=admin
        - RABBITMQ_DEFAULT_PASS=Rabbit@9527
    ports:
        - 6672:5672
        - 16672:15672